name: 'setup-java'
description: 'Setup Java'
inputs:
  java-version:
    description: 'The Java version to set up'
    required: true
    default: '17'
  distribution:
    description: 'The distribution to use'
    required: true
    default: 'temurin'
runs: 
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}